SNP_SHARED_MAKEFILE := $(if $(SNP_SHARED_MAKEFILE),$(SNP_SHARED_MAKEFILE),../../shared.mk)

TARGET     := bin/bit-manipulation
SOURCES    := src/main.c
TSTSOURCES := tests/tests.c

include $(SNP_SHARED_MAKEFILE)
